import os

BASE_DIR = "fish_image" 

IMG_HEIGHT = 160
IMG_WIDTH = 160
BATCH_SIZE = 32  
LEARNING_RATE = 3e-4
EPOCHS = 50      
DROPOUT_RATE = 0.5
SEED = 42
SHUFFLE_BUFFER = 500

TRAIN_SPLIT = 0.7
VAL_SPLIT = 0.15
TEST_SPLIT = 0.15

LABEL_SMOOTHING = 0.1
WEIGHT_DECAY = 1e-4
USE_FOCAL_LOSS = False  
FOCAL_GAMMA = 2.0
FOCAL_ALPHA = 0.25

USE_DATA_AUGMENTATION = True
AUGMENTATION_ROTATION = 0.08
AUGMENTATION_ZOOM = 0.15
AUGMENTATION_CONTRAST = 0.1

MOBILENET_ALPHA = 0.75
MOBILENET_DROPOUT = 0.0
MOBILENET_LEARNING_RATE = 5e-4
MOBILENET_LABEL_SMOOTHING = 0.0
MOBILENET_USE_CLASS_WEIGHTS = True

USE_MIXED_PRECISION = True

TRANSFER_FREEZE_BASE = True
FINE_TUNE = True
FINE_TUNE_AT = 50  
FINE_TUNE_LR = 1e-5
FINE_TUNE_EPOCHS = 15

USE_CLASS_WEIGHTS = True
MAX_CLASS_WEIGHT = 10.0

MODELS_DIR = "models"
os.makedirs(MODELS_DIR, exist_ok=True) 

CUSTOM_CNN_PATH = os.path.join(MODELS_DIR, "custom_cnn.keras")
MOBILENET_PATH = os.path.join(MODELS_DIR, "mobilenet_scratch.keras")
RESNET_PATH = os.path.join(MODELS_DIR, "resnet_transfer.keras")
INCEPTION_PATH = os.path.join(MODELS_DIR, "inception_transfer.keras")